// Zentrale Versionsnummer der App.
// Bei jedem neuen Feature oder Bugfix hier hochzählen.
export const APP_VERSION = '1.14.32';

export const CHANGELOG = [
  {
    version: '1.14.32',
    date: '2026-06-08',
    changes: [
      'Lagerbestand zaehlt nicht mehr nur den Rohstatus lager, sondern alle nicht wirklich ausgegebenen und nicht verlorenen Bestandsteile',
      'Altbestand oder inkonsistent eingebuchte Teile mit Status ausgegeben ohne gueltige Person werden im Materialfilter als Lager angezeigt',
      'Materialliste, Dashboard, Artikelsuche, Sponsoruebersicht und Bestands-PDF nutzen dieselbe Lager-/Ausgegeben-Klassifizierung',
      'Team-Sichtbarkeit fuer Lagerware nutzt ebenfalls die neue Bestandsklassifizierung',
    ],
  },
  {
    version: '1.14.31',
    date: '2026-06-08',
    changes: [
      'Saison-Ruecklauf mit gleicher Nummer und Groesse wird global fuer den passenden Eintritt priorisiert',
      'Ruecklaufteile von austretenden Spielern/Trainern koennen nicht mehr vorher als Umbeflockung fuer andere Nummern verbraucht werden',
      'Aeltere Rueckgaben ohne gespeicherte Nummer werden ueber Ruecklaufdaten, Name, Mannschaft und Saison-Austritt robuster zugeordnet',
      'Material- und Bestellvorschlaege zeigen Saison-Ruecklauf deutlicher als Umverteilung an',
    ],
  },
  {
    version: '1.14.30',
    date: '2026-06-08',
    changes: [
      'Trikotsaetze nach Sponsor sind als eigenes Hauptmenue Sponsoren verfuegbar',
      'Sponsoren koennen mit Artikel- und optionaler Mannschaftszuordnung angelegt, bearbeitet und geloescht werden',
      'Sponsorhinweise werden in den Materiallisten direkt an Gruppen und einzelnen Materialzeilen angezeigt',
      'Neue Wareneingaenge uebernehmen passende Sponsorzuordnungen aus den Stammdaten',
    ],
  },
  {
    version: '1.14.29',
    date: '2026-06-08',
    changes: [
      'Rueckgaben behalten die Beflockungsnummer und speichern Ruecklaufdaten fuer spaetere Umverteilung',
      'Bestehende Ruecklaufteile ohne gespeicherte Nummer werden ueber Name, Mannschaft und Saison-Austritt dem vorherigen Spieler/Trainer zugeordnet',
      'Artikel- und Mannschaftsabgleich fuer Umverteilung, Umbeflockung und Bestellbedarf toleriert unterschiedliche Schreibweisen und Artikelnummern im Namen',
      'Restbestellungen pruefen direkt vor dem Anlegen erneut, ob ein passender Ruecklauf- oder Lagerbestand vorhanden ist',
    ],
  },
  {
    version: '1.14.28',
    date: '2026-06-08',
    changes: [
      'Umverteilung kann optional mannschaftsuebergreifend suchen; Standard bleibt die Bindung an dieselbe Mannschaft',
      'Gleiche Nummer und gleiche Groesse werden bei Lagerbestand und ausscheidenden Spielern/Trainern vorrangig als Umverteilung erkannt',
      'Bestellformular nutzt denselben optionalen Modus fuer mannschaftsuebergreifende Set-Umverteilung',
      'Material zeigt eine neue Trikotsatz-Uebersicht nach Sponsor, Mannschaft, Lager, Ausgabe und offenen Bestellungen',
    ],
  },
  {
    version: '1.14.27',
    date: '2026-06-08',
    changes: [
      'Bestellbedarf nutzt bei Ruecklauf-Lagerteilen nicht mehr nur die interne Artikel-ID, sondern auch Artikelnummer und Artikelname',
      'Zurueckgegebene Teile bleiben dadurch nach Katalogimporten oder Artikel-Duplikaten fuer Umverteilung verfuegbar',
      'Groessenvergleich fuer Lager, Ruecklauf, offene Bestellungen und ausgegebene Teile normalisiert Schreibweisen wie M, M Leerzeichen und 3XL/XXXL',
      'Standard-Set-Bestellungen und Materialvorschlaege vermeiden dadurch falsche Restbedarfe bei vorhandenen Ruecklaufteilen',
    ],
  },
  {
    version: '1.14.26',
    date: '2026-06-08',
    changes: [
      'Build-Stand bereinigt: lokale App-Dateien enthalten keine Merge-Konfliktmarker',
      'Vercel-Fehler durch versehentlich gepushte Konfliktmarker im Bereich getPersonItemSize abgesichert',
    ],
  },
  {
    version: '1.14.25',
    date: '2026-06-08',
    changes: [
      'Umverteilung erkennt zurueckgegebene Lagerteile mit gleicher Nummer, Mannschaft und Groesse wieder vorrangig als verwendbaren Bestand',
      'Alte Namensbeflockung blockiert nummerngleiche Ruecklaufteile nicht mehr faelschlich als Restbedarf',
      'Ruecklauf-Lagerteile werden in der Materiallogik als Umverteilung statt als Bestellung eingeordnet',
      'Fehler in der Standard-Set-Bestellung behoben: artikelgenaue Groesse wird erst nach Ermittlung des Artikels berechnet',
    ],
  },
  {
    version: '1.14.24',
    date: '2026-05-21',
    changes: [
      'Spieler und Trainer behalten standardmaessig eine Einheitsgroesse',
      'Optional kann je Person Einzelne Groessen aktiviert werden',
      'Bei Einzelgroessen wird die Groesse je Artikel des Standard-Sets gepflegt',
      'Grundbestueckung, Materialvorschlaege und Set-Bestellungen beruecksichtigen artikelgenaue Personengroessen',
    ],
  },
  {
    version: '1.14.23',
    date: '2026-05-21',
    changes: [
      'Artikel-Fotos im Artikelkatalog nutzen die gleiche Bedienlogik wie die Bedarfsmeldung',
      'Fotos koennen in Einstellungen und Material per Klick vergroessert und mit Zurueck geschlossen werden',
      'Materialliste und Lagerbestand zeigen Artikel-Fotos direkt am Artikel',
      'Artikelkatalog und Fotodarstellung wurden fuer PC, Tablet und Smartphone responsiver aufgebaut',
    ],
  },
  {
    version: '1.14.22',
    date: '2026-05-20',
    changes: [
      'Artikel koennen im Artikelkatalog unter Einstellungen grundsaetzlich von Umflockung ausgeschlossen werden',
      'Der katalogweite Ausschluss verhindert Umbeflockungsvorschlaege fuer alle Bestandsstuecke dieses Artikels',
      'Umbeflockungszeilen zeigen an, wenn der Ausschluss aus dem Artikelkatalog stammt',
    ],
  },
  {
    version: '1.14.21',
    date: '2026-05-20',
    changes: [
      'Artikel in der Umbeflockungsliste koennen jetzt per Checkbox von der Umflockung ausgeschlossen werden',
      'Ausgeschlossene Artikel werden nicht mehr als Umbeflockungsquelle vorgeschlagen',
      'Wenn durch den Ausschluss kein anderes Material passt, wandert der Bedarf in den Restbedarf fuer Bestellung',
    ],
  },
  {
    version: '1.14.20',
    date: '2026-05-20',
    changes: [
      'Textfehler im Suchbereich korrigiert: Zuruecksetzen wird wieder sauber angezeigt',
    ],
  },
  {
    version: '1.14.19',
    date: '2026-05-20',
    changes: [
      'Materialbereich zeigt jetzt einen eigenen Restbedarf fuer noch nicht gedeckte Standard-Set-Positionen',
      'Aus dem Restbedarf kann direkt eine Bestellung erzeugt werden',
      'Beim Erzeugen der Restbedarf-Bestellung werden vorhandene Ausgabe, offene Bestellungen, Umverteilung, Lagerausgabe und Umbeflockung erneut geprueft',
      'Restbedarf kann auch als PDF exportiert werden',
    ],
  },
  {
    version: '1.14.18',
    date: '2026-05-20',
    changes: [
      'Trainer-Material darf bei Umverteilung und Umbeflockung jetzt mannschaftsuebergreifend vorgeschlagen werden',
      'Spieler-Material bleibt bei Umverteilung und Lagerausgabe weiterhin an die Mannschaft gebunden',
      'Quellen aus anderen Trainer-Mannschaften werden in den Materialvorschlagslisten mit Mannschaftshinweis angezeigt',
    ],
  },
  {
    version: '1.14.17',
    date: '2026-05-20',
    changes: [
      'Die Materiallisten fuer Umverteilung, Ausgabe aus Lager und Umbeflockung haben jetzt Filter wie der Lagerbestand',
      'Filter nach Personenkreis, Mannschaft, Person, Artikel, Groesse und Freitextsuche ergaenzt',
      'PDF-Exporte der Vorschlagslisten verwenden die aktuell gefilterte Ansicht',
    ],
  },
  {
    version: '1.14.16',
    date: '2026-05-20',
    changes: [
      'Material-Vorschlagslisten beruecksichtigen jetzt Standard-Sets fuer Spieler und Trainer',
      'Trainer mit Saison-Eintritt, zugeordnetem Standard-Set oder noch fehlender Ausstattung erscheinen in Umverteilung, Ausgabe aus Lager und Umbeflockung',
      'Trainer werden in den Material-Vorschlagslisten und PDF-Ausgaben als Trainer gekennzeichnet',
    ],
  },
  {
    version: '1.14.15',
    date: '2026-05-20',
    changes: [
      'Die Liste Ausgabe aus Lager kann jetzt ebenfalls als PDF gedruckt werden',
    ],
  },
  {
    version: '1.14.14',
    date: '2026-05-20',
    changes: [
      'Umverteilung aus Material ausscheidender Spieler/Trainer wird wieder nach gleicher Mannschaft, Groesse und Nummer/Initialen bewertet',
      'Abweichender Flockname beim bisherigen Besitzer verschiebt passende Austritt-zu-Eintritt-Teile nicht mehr faelschlich in Umbeflockung',
      'Die strengere Namenspruefung bleibt fuer Lagerbestand und Reservierungen erhalten',
    ],
  },
  {
    version: '1.14.13',
    date: '2026-05-20',
    changes: [
      'Bestellungen koennen nachtraeglich bearbeitet werden',
      'Lieferant, Beflockung, Sponsorplatzierungen, Sponsor-Kennung, Notizen und Positionen lassen sich nach dem Anlegen anpassen',
      'Bearbeiten ist aus der Bestelluebersicht und aus der Detailansicht moeglich',
      'Beim Bearbeiten bleiben Status, ID, Wareneingangsbezug und verknuepfte Bedarfsmeldungen erhalten',
    ],
  },
  {
    version: '1.14.12',
    date: '2026-05-20',
    changes: [
      'Spieler koennen jetzt per Checkbox als Torwart markiert werden',
      'Standard-Sets unterstuetzen die neue Zielgruppe Nur Torwart',
      'Standard-Sets haben eine Set-Nummer und koennen als Standard markiert werden',
      'Spielern und Trainern kann ein konkretes Standard-Set zugeordnet werden; sonst greift die passende Standardauswahl',
      'Grundbestueckung, Team-Sets, Bestellvorschlaege und Materialvorschlaege beruecksichtigen Torwart-Sets getrennt von normalen Spieler-Sets',
    ],
  },
  {
    version: '1.14.11',
    date: '2026-05-20',
    changes: [
      'Materiallogik erneut geprueft und vereinheitlicht: Umverteilung vor passender Lagerausgabe vor Umbeflockung',
      'Passender Lagerbestand beruecksichtigt jetzt neben Mannschaft und Nummer/Initialen auch den hinterlegten Flocknamen',
      'Reservierungen speichern Nummer/Initialen und Namen am Bestand und werden dadurch als gedeckter Bedarf erkannt',
      'Reservierter oder passend vorbeflockter Bestand verhindert neue Bestellvorschlaege fuer denselben Spieler/Trainer und Artikel',
    ],
  },
  {
    version: '1.14.10',
    date: '2026-05-20',
    changes: [
      'Materialvorschlaege nutzen jetzt fest die Reihenfolge: Umverteilung Austritt zu Eintritt, passende Lagerausgabe, danach Umbeflockung',
      'Passender Lagerbestand wird im Materialbereich als eigene Kategorie Ausgabe aus Lager angezeigt',
      'Umbeflockung wird erst vorgeschlagen, wenn keine passende Umverteilung und keine passende Lagerausgabe verfuegbar ist',
      'Reservieren in der Material-Ausgabe funktioniert jetzt direkt aus dem Ausgabedialog',
    ],
  },
  {
    version: '1.14.9',
    date: '2026-05-20',
    changes: [
      'Saison-Umverteilung priorisiert jetzt ausscheidende Personen gleicher Mannschaft, gleicher Groesse und gleicher Nummer/Initialen vor Lagerbestand',
      'Bestell- und Grundbestueckungsvorschlaege nutzen dieselbe Prioritaet fuer Eintritt/Austritt',
      'Umverteilung und Umbeflockung koennen jeweils als PDF gedruckt werden',
      'Zeichensatzfehler im neuen Materialbereich wurden korrigiert',
    ],
  },
  {
    version: '1.14.8',
    date: '2026-05-20',
    changes: [
      'Material hat jetzt einen eigenen Bereich fuer Umverteilung und Umbeflockung angelehnt an die Materialliste',
      'Vorschlaege aktualisieren sich aus offenen Bestellungen, Saisonstatus, Standard-Sets und aktuellem Bestand',
      'Umverteilung und Umbeflockung werden getrennt als Alt-zu-Neu-Listen angezeigt',
      'Lagerbestand kann direkt aus dem Vorschlag heraus fuer einen Spieler oder Trainer reserviert werden',
    ],
  },
  {
    version: '1.14.7',
    date: '2026-05-20',
    changes: [
      'Offene Bestellungen decken den Bedarf und verhindern erneute Bestellzeilen für denselben Spieler/Trainer, Artikel und Größe',
      'Standard-Set-Bestellungen berücksichtigen bereits im aktuellen Bestellentwurf vorhandene Positionen',
      'Set-Mengen werden pro Stück gegen ausgegebenes Material, offene Bestellungen, Lagerbestand, Umverteilung und Umbeflockung verrechnet',
      'Set-Auswertung weist bereits gedeckte Positionen, Umverteilung und Umbeflockung transparenter aus',
    ],
  },
  {
    version: '1.14.6',
    date: '2026-05-20',
    changes: [
      'Standard-Set-Bestellvorschlag berücksichtigt jetzt auch Lagerbestand vor dem Erzeugen neuer Bestellzeilen',
      'Passender Lagerbestand verhindert eine Bestellung; abweichend beflockter Lagerbestand erscheint als Umbeflockungsvorschlag',
      'Set-Auswertung ist klar nach Umverteilung alt-neu und Umbeflockung alt-neu getrennt',
      'Lagerbestand, reservierter Lagerbestand und Material ausscheidender Personen werden transparent als Quelle ausgewiesen',
    ],
  },
  {
    version: '1.14.5',
    date: '2026-05-20',
    changes: [
      'Normales Bestellformular wertet Standard-Sets jetzt ebenfalls gegen Saison-Umverteilung aus',
      'Set anwenden erzeugt keine Bestellzeilen mehr, wenn passende Teile ausscheidender Personen gleicher Mannschaft und Größe vorhanden sind',
      'Set-Auswertung zeigt sichtbar an, welche Positionen durch Umverteilung gedeckt sind und wo Umbeflockung/Nummernwechsel zu prüfen ist',
      'Fall Emre Hamut/Felipe Alves Nr. 11 wird im normalen Bestellformular nicht mehr als Bestellung erzeugt, wenn die passenden Felipe-Teile ausgegeben sind',
    ],
  },
  {
    version: '1.14.4',
    date: '2026-05-20',
    changes: [
      'Bestelllogik erneut gehärtet: Normale Standard-Set-Bestellungen berücksichtigen Saison-Eintritt/-Austritt jetzt ebenfalls',
      'Austritte werden aus Set-Bestellungen und Grundbestückungsvorschlägen ausgeschlossen, sofern sie nicht zusätzlich als Eintritt markiert sind',
      'Umverteilung vergleicht jetzt die effektive Nummer des Materials, also notfalls die Nummer des bisherigen Besitzers',
      'Saisonwechsel-Fall Emre Hamut/Felipe Alves mit Nummer 11 wird dadurch auch dann als Umverteilung erkannt, wenn am Material selbst keine assignedNumber gespeichert ist',
      'Umbeflockungshinweis ergänzt: Abweichende Nummern werden vorgeschlagen, wenn Korrektur Ausgabemengen deaktiviert ist',
    ],
  },
  {
    version: '1.14.3',
    date: '2026-05-20',
    changes: [
      'Bestellvorschläge schließen Bestands-Spieler/Trainer ohne Saisonmarkierung standardmäßig aus; per Checkbox können sie wieder einbezogen werden',
      'Umverteilung aus Material ausscheidender Personen wird jetzt auch im Korrekturmodus geprüft, sofern keine Umbeflockung nötig ist',
      'Umverteilungsvorschläge beschränken sich auf gleiche Personenart, Mannschaft, Artikel und Größe',
      'Saisonwechsel-Fall mit gleicher Nummer, z. B. Nr. 11 Hamut/Alves in der Ersten, wird dadurch als Umverteilung statt Bestellung vorgeschlagen',
    ],
  },
  {
    version: '1.14.2',
    date: '2026-05-20',
    changes: [
      'Bestellvorschläge für Grundbestückung berücksichtigen Saison-Eintritt und Saison-Austritt',
      'Team-Grundbestückung überspringt ausscheidende Personen und nutzt Material ausscheidender Personen gleicher Größe als Umverteilung',
      'Umverteilungen und passende Lager-/Reservierungsbestände werden nicht als fehlender Bestand bestellt',
      'Umbeflockungen können weiterhin per Checkbox in eine Bestellung übernommen werden, inklusive Verweis auf das passende Material',
      'Lagerteile können für neue Spieler oder Trainer reserviert werden und werden dadurch aus fremden Bestellvorschlägen herausgehalten',
    ],
  },
  {
    version: '1.14.1',
    date: '2026-05-20',
    changes: [
      'Doppelte Trikotnummern oder Trainer-Initialen sind für Saisonwechsel erlaubt, wenn eine Person als Eintritt und die andere als Austritt markiert ist',
      'Bedarfsmeldungen priorisieren bei Saisonwechsel-Doppelungen die eintretende bzw. nicht austretende Person',
    ],
  },
  {
    version: '1.14.0',
    date: '2026-05-20',
    changes: [
      'Artikelsuche unter Material, Spieler und Trainer ergänzt: Suche nach Trikotnummer/Initialen mit Mannschaftsfilter',
      'Suchergebnisse zeigen, ob Artikel im Lager, beim Spieler/Trainer ausgegeben oder bestellt sind',
      'Optional kann die Suche alle zugeordneten Teile einer gefundenen Person anzeigen',
      'Artikelkatalog unterstützt Fotos je Artikel; diese erscheinen in Suche und Materialübersichten',
      'Einstellungen sind in Untermenüs für Allgemein, Mannschaften, Artikel & Sets, Lieferanten sowie Pfandregeln gegliedert',
      'Übergabeprotokoll für ausgegebene Teile als PDF mit Pfandregel und digitaler Unterschrift ergänzt',
      'Rückgabeprotokoll als PDF mit Zustand, Pfandabrechnung und digitaler Unterschrift ergänzt',
      'Spieler und Trainer können für Eintritt oder Ausscheiden zur neuen Saison markiert werden',
    ],
  },
  {
    version: '1.13.0',
    date: '2026-05-20',
    changes: [
      'Pre-Production Security Review umgesetzt: Auth- und Daten-API gehärtet',
      'Login und Setup setzen bevorzugt HttpOnly-Session-Cookies statt Client-Token im localStorage',
      'API-Routen liefern Sicherheitsheader und loggen Fehler mit Request-ID ohne sensible Daten',
      'Datenzugriffe werden nach Rolle und Mannschaft gefiltert, Schreibzugriffe serverseitig autorisiert',
      'REST-DB-Service schützt Daten vor unberechtigtem Überschreiben und merge-t Bestände scoped nach ID',
      'Logout-Route ergänzt und Auth-Client auf Cookie-basierte Requests umgestellt',
      'Tests für Security-Header, Auth-Cookies und Datenzugriff ergänzt',
    ],
  },
  {
    version: '1.12.0',
    date: '2026-05-18',
    changes: [
      'Umbeflockungslisten koennen jetzt zusaetzlich als PDF exportiert werden',
      'Aus der Spieler-/Trainer- oder Team-Grundbestueckung kann direkt eine Bestellung fuer fehlende Bestandsartikel erzeugt werden',
      'Umbeflockungspositionen koennen pro Zeile optional per Checkbox in diese Bestellung aufgenommen werden',
      'Die Materialuebersicht laesst sich gruppiert nach Artikel, Team oder Spieler/Trainer anzeigen',
    ],
  },
  {
    version: '1.11.2',
    date: '2026-05-18',
    changes: [
      'Grundbestückung präzisiert: Im Korrekturmodus wird immer die im Spieler/Trainer hinterlegte Nummer bzw. Initiale verbindlich zugewiesen',
      'Korrektur Ausgabemengen erzeugt keine Umbeflockungsvorschläge mehr und verwendet keine abweichend beflockten Lagerteile',
      'Standard-Sets bleiben direkt pro Spieler/Trainer sowie teamweit auswählbar',
    ],
  },
  {
    version: '1.11.1',
    date: '2026-05-18',
    changes: [
      'Team-Pfandregeln unterstützen jetzt zusätzlich die Auswahl „ohne Pfand"',
      'Standard-Pfandregel ist immer Pauschal, auch wenn für ein Team noch keine eigene Regel gespeichert wurde',
      'Bei „ohne Pfand" wird in der Pfandkasse keine Pfandeinnahme angelegt und die Rückgabe ohne Pfandabrechnung verarbeitet',
      'Team-Pfandbetrag wird bei „ohne Pfand" automatisch auf 0 gesetzt und deaktiviert',
    ],
  },
  {
    version: '1.11.0',
    date: '2026-05-18',
    changes: [
      'Spieler-/Trainerlisten, Materiallisten und Bestelllisten sind jetzt per Klick auf die Spaltenüberschrift sortierbar',
      'Sortierrichtung wechselt pro Klick zwischen aufsteigend und absteigend',
      'Spaltenüberschriften zeigen Sortierhinweise mit Pfeilsymbolen',
      'Standard-Sets können jetzt nicht nur je Spieler/Trainer, sondern auch teamweit verarbeitet werden',
      'Team-Grundbestückung erzeugt Vorschläge aus Lagerbestand, Korrekturbuchungen und Umbeflockungsbedarf für die gesamte Mannschaft',
      'Teamweite Umbeflockungsliste kann als CSV exportiert werden',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-05-18',
    changes: [
      'Neue Grundbestückung direkt an Spieler/Trainer: Standard-Set prüfen und fehlende Erstausstattung nachträglich einpflegen',
      'Korrekturmodus für Ausgabemengen ergänzt: bereits ausgegebene Teile können ohne vorherigen Lagerbestand als Inventar-Korrektur angelegt werden',
      'Materialvorschläge nutzen Lagerbestand mit passender Nummer/Initialen und schlagen alternativ größenpassende Teile mit abweichender Beflockung vor',
      'Bereits ausgegebene Teile werden bei der Erstausstattungsprüfung auch über Nummer/Initialen berücksichtigt',
      'Umbeflockungsliste als CSV erzeugbar, wenn Lagerteile von alter auf neue Nummer/Initialen geändert werden müssen',
      'Umbeflockung kann beim Ausgeben von Material direkt als Alt-zu-Neu-Wechsel am Materialteil erfasst werden',
      'Materiallisten zeigen Umbeflockungsbedarf als Hinweis am betroffenen Artikel',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-05-18',
    changes: [
      'Login- und Setup-Flow robuster gemacht: Auth-Status wird sauber ausgewertet und Fehler werden im Frontend verständlich angezeigt',
      'API-Fehlerlogging mit Fehler-ID ergänzt, ohne Passwörter oder Tokens in Logs zu schreiben',
      'JWT_SECRET ist jetzt Pflicht und muss in Vercel mindestens 32 Zeichen lang gesetzt sein',
      'Material-Wareneingang schützt bestehenden Bestand vor Überschreiben: neue Inventarteile werden per ID in den Bestand gemergt',
      'Materialübersicht zeigt Nummern/Initialen jetzt auch für eingebuchte Lagerartikel mit vorerfasster Beflockung',
      'Eingebuchte Artikel behalten Nummer/Initialen, Flockname, Sponsor-Kennung und Bestellbezug im Inventar',
      'Gruppierte und einzelne Materiallisten zeigen Nr./Init. als eigene Spalte',
      'PDF-Bestandsliste enthält Nr./Init. ebenfalls als eigene Spalte',
      'Bestellungen können über eine Sponsor-Kennung / Trikotsatz-ID identifiziert werden',
      'Wareneingang zeigt Sponsor-Kennung in der Bestellauswahl an',
      'Pfandregeln können je Mannschaft individuell überschrieben werden',
      'Lokale optimistische Anzeige nach Material-Merge hält den vollständigen Bestand sichtbar',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-05-08',
    changes: [
      'Neues Vereinslogo + Favicon-Set aus dem aktuellen FC-Frohlinde-Wappen erzeugt',
      'Logo erscheint jetzt im App-Header (30×30 px) und auf der Login-Seite (60×60)',
      'Standard-Sets in den Einstellungen vollständig konfigurierbar: anlegen, umbenennen, kopieren, löschen — pro Set mit Ziel „Spieler", „Trainer" oder „beide"',
      'Beim Bestellen wird jetzt eine Set-Auswahl (Dropdown) angeboten, die nur Personen ohne diese Ausstattung berücksichtigt',
      'Lager-Trennung pro Mannschaft: Material wird beim Wareneingang automatisch dem Team der Bestellung zugeordnet',
      'Beim freien Einbuchen kann die Mannschaft pro Zeile gewählt oder global voreingestellt werden',
      'Lagerübersicht aggregiert pro Artikel × Größe × Mannschaft — eine eigene Spalte „Mannschaft"',
      'Bei der Material-Ausgabe sind nur Personen aus dem Team des Lagerbestands wählbar',
      'Material-Ausgabe-Formular akzeptiert Initialen für Trainer (1–3 Buchstaben) und Nummern für Spieler',
      'Spieler/Trainer-Löschen ist gesperrt, solange Material ausgegeben oder Pfand offen ist — Schutzregel auch für Admins',
      'Konfigurierbare Berechtigungen pro Nutzer in der Benutzerverwaltung: Personen löschen, Bestellungen, Material, Pfand, Bedarfsmeldungen',
      'Default für neue Nutzer: keine Lösch-Rechte; alle anderen Bereiche aktiv',
      'Bedarfsmeldung: Name wird automatisch aus Mannschaft + Nummer/Initialen identifiziert und angezeigt',
      'Submit ist gesperrt, wenn keine Person zur Eingabe gefunden wird — verhindert Tippfehler',
      'PDF-Bestandsliste enthält am Ende eine Übersicht aller belegten und freien Trikotnummern (1–99) sowie Trainer-Initialen pro Mannschaft',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-05-08',
    changes: [
      'Hotfix: Weiße Seite nach 1.8.0-Update behoben — Hooks waren nach einem bedingten Return platziert',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-05-08',
    changes: [
      'Nutzer können auf eine oder mehrere Mannschaften zugeordnet werden',
      'Inline-Bearbeiten in der Nutzerverwaltung mit Multi-Select für Teams',
      'Settings und Nutzerverwaltung nur für Admins zugänglich',
      'Auto-Refresh des User-Stands beim App-Start',
    ],
  },
  {
    version: '1.7.5',
    date: '2026-05-08',
    changes: [
      'Apple-Touch-Icon mit weißem Hintergrund neu erzeugt (iOS füllt sonst schwarz)',
      'Dashboard zeigt pro Mannschaft Spieler-, Trainer- und Material-Anzahl',
      'Stats-Karte „Spieler & Trainer" ersetzt die reine Spielerzahl',
      'Artikelkatalog: Spalten-Layout neu balanciert',
      'Material einbuchen komplett überarbeitet: Modus „Aus Bestellung" mit Wareneingang und Mengenabgleich',
      'Bestell-Status wird nach Wareneingang automatisch auf „teilweise geliefert" oder „geliefert" gesetzt',
      'Eingehende Bedarfsmeldungen haben jetzt immer Status „offen"',
      'Foto-Pflicht bei den Gründen „verschlissen", „Flock kaputt", „beschädigt"',
      'Flock-Liste zeigt nur noch Nummern/Initialen',
      'Material & Bestand: PDF-Listendruck mit Filter (Status, Personenkreis, Mannschaft, Einzelperson)',
      'Trainer-Kennzeichnung in allen Listen vereinheitlicht',
    ],
  },
  {
    version: '1.7.4',
    date: '2026-05-08',
    changes: [
      'Standard-Sets für Spieler und Trainer in den Einstellungen konfigurierbar (jeder Artikel mit eigener Stückzahl)',
      'Im Bestellformular zwei Buttons: „Spieler-Set" und „Spieler + Trainer-Set" — erzeugt die komplette Erstausstattung in einem Klick',
      'Bestellliste und Flock-Liste sind jetzt nach Artikel × Größe gruppiert — keine Einzelposten mehr',
      'Pro Gruppe werden alle Beflockungen mit Nummer/Initialen und Flock-Name in einer Spalte aufgelistet',
      'Lagerware ohne Beflockung wird separat ausgewiesen',
      'Bestellliste mit Gesamtsumme am Ende',
    ],
  },
  {
    version: '1.7.3',
    date: '2026-05-08',
    changes: [
      'Trainer haben jetzt Initialen statt Rückennummer (1–3 Buchstaben, automatisch Großbuchstaben)',
      'Konflikt-Check pro Mannschaft funktioniert für Initialen wie für Spielernummern',
      'Trainer-CSV-Import mit eigener Vorlage (Spalte „Initialen", Beispieldaten)',
      'ReportForm akzeptiert sowohl Nummern als auch Initialen — automatische Erkennung im Backend',
      'Bestellungs-Import-Bug behoben: Artikelnummern aus CSV werden jetzt korrekt im Katalog angezeigt',
      'Artikelkatalog-Import unterstützt zusätzlich die Spalte „Lieferant" (Auflösung über Name, Warnung bei unbekannten Lieferanten)',
      'Neuer Button „Personen auswählen" im Bestellformular: Multi-Select für Spieler + Trainer mit Filtern (Mannschaft, Suche)',
      'Bei Sammelpositionen mit Menge > 1 erscheint ein „verteilen"-Button — die Menge wird auf ausgewählte Personen aufgesplittet',
      'Bestellpositionen zeigen Artikelnummer im Dropdown ([T-001] Trainingsshirt)',
      'Artikelnummer wird im PDF-Export, in beiden CSV-Listen und in der Bestelldetail-Ansicht ausgewiesen',
      'Trainer in Bestelltabellen mit TRAINER-Badge gekennzeichnet, Initialen werden in Bebas Neue dargestellt',
      'Mannschaft im Bestellformular dient jetzt als optionaler Filter — auch Einzelteil-Bestellungen profitieren',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-05-08',
    changes: [
      'Material-Übersicht standardmäßig gruppiert: pro Artikel × Größe Summen für Lager / Ausgegeben / Markiert / Gesamt',
      'Klick auf eine Gruppenzeile öffnet die Einzelteile mit Status, Zuordnung und Zustand',
      'Buttons „Alle auf" / „Alle zu" zum schnellen Auf-/Zuklappen aller Gruppen',
      'Toggle „Gruppiert" / „Einzeln" — die alte ungruppierte Liste bleibt zugänglich',
      'Summenzeile am Tabellenende zeigt Gesamtbestand auf einen Blick',
      'Größen werden in natürlicher Reihenfolge sortiert (XS, S, M, L, XL, XXL, dann Jugend-Größen)',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-05-08',
    changes: [
      'Vereinslogo auf der Login-Seite (100×100) und in der öffentlichen Bedarfsmeldung (80×80)',
      'Favicon im Browser-Tab und auf dem Home-Bildschirm (alle gängigen Größen 16/32/48/96/180/192/512 plus .ico)',
      'Vereinsblau als Theme-Farbe im mobilen Browser-UI',
      'Tab-Titel zeigt jetzt „FC Frohlinde · Trikotverwaltung"',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-08',
    changes: [
      'Lieferanten-Verwaltung in den Einstellungen (Name, Typ, Kontakt, Notizen)',
      'In Bestellungen wählbar: Artikel-Lieferant und Beflockungs-Quelle (Im Haus / Lieferant / extern)',
      'Bei externer Beflockung separater Flock-Lieferant aus der Liste',
      'Material-CSV-Import mit drei Modi: Aktualisieren über Artikelnummer / Hinzufügen / Komplett ersetzen',
      'CSV-Import erkennt Spalten Artikelnummer, Name, Preis, Ersatzwert, Lieferant automatisch',
      'Vorschau vor dem Import zeigt, welche Artikel aktualisiert / neu hinzugefügt werden',
      'Standard-Lieferant für CSV-Zeilen ohne Zuordnung kann beim Import gesetzt werden',
      'Artikelkatalog mit zusätzlichen Spalten: Artikelnummer und Lieferant',
      'Bedarfsmeldungen werden gesperrt, sobald sie in eine Bestellung übernommen wurden (kein doppelter Bestelleingang)',
      'Bestellungen können zusammengeführt werden (Sammelbestellung) — Lines, Bedarfsmeldungen und Sponsoren werden verschmolzen',
      'Beim Löschen einer Bestellung werden gesperrte Bedarfsmeldungen automatisch wieder freigegeben',
      'Sammelbestellungen werden in Übersicht und PDF gekennzeichnet',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-07',
    changes: [
      'Trainer-Bereich mit eigenem Tab und kompletter Logik analog zu Spielern',
      'Automatische Personen-Identifikation bei Bedarfsmeldung (Mannschaft + Nummer)',
      'Automatische Material-Markierung beim Eingang einer Meldung (kein manuelles Klicken mehr)',
      'Foto-Button in der Bedarfs-Übersicht jetzt immer sichtbar (in der Artikel-Spalte)',
      'Fotos werden aggressiver komprimiert (max. 500 KB) für stabile Speicherung',
      'Trainer werden überall mit TRAINER-Badge gekennzeichnet (Material, Pfand, Bestellungen)',
      'Material-Markierungen sind jetzt in der Spieler-/Trainer-Liste als ⚠ Badge sichtbar',
    ],
  },
  {
    version: '1.5.2',
    date: '2026-05-07',
    changes: [
      'Hotfix: MIME-Type-Header für JS-Module in vercel.json korrigiert',
      'PDF-Bibliotheken werden jetzt direkt ins Hauptbundle gepackt (kein Lazy-Loading mehr)',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-05-07',
    changes: [
      'Hotfix: PDF-Export funktioniert jetzt zuverlässig (statischer Import von jspdf, Side-Effect-API)',
      'PDF-Fehler werden sichtbar angezeigt statt stillschweigend zu scheitern',
      'Sicherer Dateiname beim PDF-Speichern',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-07',
    changes: [
      'Mailversand auf SMTP umgestellt (statt Resend) — funktioniert mit jedem Mail-Provider',
      'Test-Mail-Funktion in den Einstellungen mit SMTP-Statusanzeige',
      'Anleitung für SMTP-Einrichtung direkt in der App (mit Beispielen für IONOS, Strato, Telekom, Gmail, M365)',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-05-07',
    changes: [
      'FCF-Pfandordnung 2025 als Standard hinterlegt (Pfand 70 €, 8 Standardteile mit Ersatzwerten)',
      'Zwei Pfandmodi: Pauschal-Modus (FCF-Standard) und Saison-Abschreibung (alt)',
      'Ersatzwert pro Artikel im Katalog editierbar',
      'Total-Verfall des Pfands per Checkbox bei Rückgabe (Punkt 8 Pfandordnung)',
      'Auszug der Pfand- & Kleiderordnung in den Einstellungen',
      'Fotos werden nach 90 Tagen automatisch aus der Datenbank gelöscht',
      'Quick-Action "FCF-Pfandordnung laden" stellt Defaults wieder her',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-07',
    changes: [
      'Foto-Upload bei Bedarfsmeldungen (Browser-Komprimierung auf max. 1280px / ~150 KB)',
      'Foto-Anzeige in der Bedarfsübersicht (Klick öffnet Großansicht)',
      'PDF-Export für Bestellungen mit integrierter Flock-Liste, Sponsoren und Vereins-Branding',
      'Badge mit Anzahl offener Bedarfsmeldungen am Tab "Bedarf"',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-05-07',
    changes: [
      'Hotfix: ReferenceError beim Öffnen der Einstellungen behoben (übersehene Konstante)',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-05-07',
    changes: [
      'Hotfix: Crash beim Öffnen der Einstellungen behoben (Default-Werte für conditionFactors abgesichert)',
      'Error-Boundary: Fehler in einzelnen Bereichen blockieren nicht mehr die ganze App',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-05-07',
    changes: [
      'Bedarfsmeldung für Spieler ohne Login',
      'Editierbare Pfandregeln (Saison-Abschreibung, Zustandsfaktoren)',
      'Wochenbericht über offene Bedarfsmeldungen',
      'Mailversand des Wochenberichts (mit Resend)',
      'Sponsoren-Platzierungen in Bestellungen (Brust, Rücken, Ärmel)',
      'Automatische Material-Markierung aus Spieler-Meldungen',
      'Versionsnummer und Changelog in Einstellungen',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-07',
    changes: [
      'CSV-Import für Spieler mit Validierung und Vorschau',
      'Editorial-Design "Dorfverein" (Vereinsblau, Playfair, Bebas Neue)',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-05-07',
    changes: [
      'Spieler- und Mannschaftsverwaltung',
      'Material- und Bestandsführung',
      'Pfandkasse mit Saison-Rückgabe und Zeitwertberechnung',
      'Bestellungen mit Flock-Liste',
      'Multi-User-Login mit Admin-Rolle',
      'Vercel KV als Datenspeicher',
    ],
  },
];
