// Zentrale Versionsnummer der App.
// Bei jedem neuen Feature oder Bugfix hier hochzählen.
export const APP_VERSION = '1.12.0';

export const CHANGELOG = [
  {
    version: '1.12.0',
    date: '2026-05-18',
    changes: [
      'Umbeflockungslisten koennen jetzt zusaetzlich als PDF exportiert werden',
      'Aus der Spieler-/Trainer- oder Team-Grundbestueckung kann direkt eine Bestellung fuer fehlende Bestandsartikel erzeugt werden',
      'Umbeflockungspositionen koennen pro Zeile optional per Checkbox in diese Bestellung aufgenommen werden',
      'Die Materialuebersicht laesst sich gruppiert nach Artikel, Team oder Spieler/Trainer anzeigen',
    ],
  },
  {
    version: '1.11.2',
    date: '2026-05-18',
    changes: [
      'Grundbestückung präzisiert: Im Korrekturmodus wird immer die im Spieler/Trainer hinterlegte Nummer bzw. Initiale verbindlich zugewiesen',
      'Korrektur Ausgabemengen erzeugt keine Umbeflockungsvorschläge mehr und verwendet keine abweichend beflockten Lagerteile',
      'Standard-Sets bleiben direkt pro Spieler/Trainer sowie teamweit auswählbar',
    ],
  },
  {
    version: '1.11.1',
    date: '2026-05-18',
    changes: [
      'Team-Pfandregeln unterstützen jetzt zusätzlich die Auswahl „ohne Pfand"',
      'Standard-Pfandregel ist immer Pauschal, auch wenn für ein Team noch keine eigene Regel gespeichert wurde',
      'Bei „ohne Pfand" wird in der Pfandkasse keine Pfandeinnahme angelegt und die Rückgabe ohne Pfandabrechnung verarbeitet',
      'Team-Pfandbetrag wird bei „ohne Pfand" automatisch auf 0 gesetzt und deaktiviert',
    ],
  },
  {
    version: '1.11.0',
    date: '2026-05-18',
    changes: [
      'Spieler-/Trainerlisten, Materiallisten und Bestelllisten sind jetzt per Klick auf die Spaltenüberschrift sortierbar',
      'Sortierrichtung wechselt pro Klick zwischen aufsteigend und absteigend',
      'Spaltenüberschriften zeigen Sortierhinweise mit Pfeilsymbolen',
      'Standard-Sets können jetzt nicht nur je Spieler/Trainer, sondern auch teamweit verarbeitet werden',
      'Team-Grundbestückung erzeugt Vorschläge aus Lagerbestand, Korrekturbuchungen und Umbeflockungsbedarf für die gesamte Mannschaft',
      'Teamweite Umbeflockungsliste kann als CSV exportiert werden',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-05-18',
    changes: [
      'Neue Grundbestückung direkt an Spieler/Trainer: Standard-Set prüfen und fehlende Erstausstattung nachträglich einpflegen',
      'Korrekturmodus für Ausgabemengen ergänzt: bereits ausgegebene Teile können ohne vorherigen Lagerbestand als Inventar-Korrektur angelegt werden',
      'Materialvorschläge nutzen Lagerbestand mit passender Nummer/Initialen und schlagen alternativ größenpassende Teile mit abweichender Beflockung vor',
      'Bereits ausgegebene Teile werden bei der Erstausstattungsprüfung auch über Nummer/Initialen berücksichtigt',
      'Umbeflockungsliste als CSV erzeugbar, wenn Lagerteile von alter auf neue Nummer/Initialen geändert werden müssen',
      'Umbeflockung kann beim Ausgeben von Material direkt als Alt-zu-Neu-Wechsel am Materialteil erfasst werden',
      'Materiallisten zeigen Umbeflockungsbedarf als Hinweis am betroffenen Artikel',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-05-18',
    changes: [
      'Login- und Setup-Flow robuster gemacht: Auth-Status wird sauber ausgewertet und Fehler werden im Frontend verständlich angezeigt',
      'API-Fehlerlogging mit Fehler-ID ergänzt, ohne Passwörter oder Tokens in Logs zu schreiben',
      'JWT_SECRET ist jetzt Pflicht und muss in Vercel mindestens 32 Zeichen lang gesetzt sein',
      'Material-Wareneingang schützt bestehenden Bestand vor Überschreiben: neue Inventarteile werden per ID in den Bestand gemergt',
      'Materialübersicht zeigt Nummern/Initialen jetzt auch für eingebuchte Lagerartikel mit vorerfasster Beflockung',
      'Eingebuchte Artikel behalten Nummer/Initialen, Flockname, Sponsor-Kennung und Bestellbezug im Inventar',
      'Gruppierte und einzelne Materiallisten zeigen Nr./Init. als eigene Spalte',
      'PDF-Bestandsliste enthält Nr./Init. ebenfalls als eigene Spalte',
      'Bestellungen können über eine Sponsor-Kennung / Trikotsatz-ID identifiziert werden',
      'Wareneingang zeigt Sponsor-Kennung in der Bestellauswahl an',
      'Pfandregeln können je Mannschaft individuell überschrieben werden',
      'Lokale optimistische Anzeige nach Material-Merge hält den vollständigen Bestand sichtbar',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-05-08',
    changes: [
      'Neues Vereinslogo + Favicon-Set aus dem aktuellen FC-Frohlinde-Wappen erzeugt',
      'Logo erscheint jetzt im App-Header (30×30 px) und auf der Login-Seite (60×60)',
      'Standard-Sets in den Einstellungen vollständig konfigurierbar: anlegen, umbenennen, kopieren, löschen — pro Set mit Ziel „Spieler", „Trainer" oder „beide"',
      'Beim Bestellen wird jetzt eine Set-Auswahl (Dropdown) angeboten, die nur Personen ohne diese Ausstattung berücksichtigt',
      'Lager-Trennung pro Mannschaft: Material wird beim Wareneingang automatisch dem Team der Bestellung zugeordnet',
      'Beim freien Einbuchen kann die Mannschaft pro Zeile gewählt oder global voreingestellt werden',
      'Lagerübersicht aggregiert pro Artikel × Größe × Mannschaft — eine eigene Spalte „Mannschaft"',
      'Bei der Material-Ausgabe sind nur Personen aus dem Team des Lagerbestands wählbar',
      'Material-Ausgabe-Formular akzeptiert Initialen für Trainer (1–3 Buchstaben) und Nummern für Spieler',
      'Spieler/Trainer-Löschen ist gesperrt, solange Material ausgegeben oder Pfand offen ist — Schutzregel auch für Admins',
      'Konfigurierbare Berechtigungen pro Nutzer in der Benutzerverwaltung: Personen löschen, Bestellungen, Material, Pfand, Bedarfsmeldungen',
      'Default für neue Nutzer: keine Lösch-Rechte; alle anderen Bereiche aktiv',
      'Bedarfsmeldung: Name wird automatisch aus Mannschaft + Nummer/Initialen identifiziert und angezeigt',
      'Submit ist gesperrt, wenn keine Person zur Eingabe gefunden wird — verhindert Tippfehler',
      'PDF-Bestandsliste enthält am Ende eine Übersicht aller belegten und freien Trikotnummern (1–99) sowie Trainer-Initialen pro Mannschaft',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-05-08',
    changes: [
      'Hotfix: Weiße Seite nach 1.8.0-Update behoben — Hooks waren nach einem bedingten Return platziert',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-05-08',
    changes: [
      'Nutzer können auf eine oder mehrere Mannschaften zugeordnet werden',
      'Inline-Bearbeiten in der Nutzerverwaltung mit Multi-Select für Teams',
      'Settings und Nutzerverwaltung nur für Admins zugänglich',
      'Auto-Refresh des User-Stands beim App-Start',
    ],
  },
  {
    version: '1.7.5',
    date: '2026-05-08',
    changes: [
      'Apple-Touch-Icon mit weißem Hintergrund neu erzeugt (iOS füllt sonst schwarz)',
      'Dashboard zeigt pro Mannschaft Spieler-, Trainer- und Material-Anzahl',
      'Stats-Karte „Spieler & Trainer" ersetzt die reine Spielerzahl',
      'Artikelkatalog: Spalten-Layout neu balanciert',
      'Material einbuchen komplett überarbeitet: Modus „Aus Bestellung" mit Wareneingang und Mengenabgleich',
      'Bestell-Status wird nach Wareneingang automatisch auf „teilweise geliefert" oder „geliefert" gesetzt',
      'Eingehende Bedarfsmeldungen haben jetzt immer Status „offen"',
      'Foto-Pflicht bei den Gründen „verschlissen", „Flock kaputt", „beschädigt"',
      'Flock-Liste zeigt nur noch Nummern/Initialen',
      'Material & Bestand: PDF-Listendruck mit Filter (Status, Personenkreis, Mannschaft, Einzelperson)',
      'Trainer-Kennzeichnung in allen Listen vereinheitlicht',
    ],
  },
  {
    version: '1.7.4',
    date: '2026-05-08',
    changes: [
      'Standard-Sets für Spieler und Trainer in den Einstellungen konfigurierbar (jeder Artikel mit eigener Stückzahl)',
      'Im Bestellformular zwei Buttons: „Spieler-Set" und „Spieler + Trainer-Set" — erzeugt die komplette Erstausstattung in einem Klick',
      'Bestellliste und Flock-Liste sind jetzt nach Artikel × Größe gruppiert — keine Einzelposten mehr',
      'Pro Gruppe werden alle Beflockungen mit Nummer/Initialen und Flock-Name in einer Spalte aufgelistet',
      'Lagerware ohne Beflockung wird separat ausgewiesen',
      'Bestellliste mit Gesamtsumme am Ende',
    ],
  },
  {
    version: '1.7.3',
    date: '2026-05-08',
    changes: [
      'Trainer haben jetzt Initialen statt Rückennummer (1–3 Buchstaben, automatisch Großbuchstaben)',
      'Konflikt-Check pro Mannschaft funktioniert für Initialen wie für Spielernummern',
      'Trainer-CSV-Import mit eigener Vorlage (Spalte „Initialen", Beispieldaten)',
      'ReportForm akzeptiert sowohl Nummern als auch Initialen — automatische Erkennung im Backend',
      'Bestellungs-Import-Bug behoben: Artikelnummern aus CSV werden jetzt korrekt im Katalog angezeigt',
      'Artikelkatalog-Import unterstützt zusätzlich die Spalte „Lieferant" (Auflösung über Name, Warnung bei unbekannten Lieferanten)',
      'Neuer Button „Personen auswählen" im Bestellformular: Multi-Select für Spieler + Trainer mit Filtern (Mannschaft, Suche)',
      'Bei Sammelpositionen mit Menge > 1 erscheint ein „verteilen"-Button — die Menge wird auf ausgewählte Personen aufgesplittet',
      'Bestellpositionen zeigen Artikelnummer im Dropdown ([T-001] Trainingsshirt)',
      'Artikelnummer wird im PDF-Export, in beiden CSV-Listen und in der Bestelldetail-Ansicht ausgewiesen',
      'Trainer in Bestelltabellen mit TRAINER-Badge gekennzeichnet, Initialen werden in Bebas Neue dargestellt',
      'Mannschaft im Bestellformular dient jetzt als optionaler Filter — auch Einzelteil-Bestellungen profitieren',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-05-08',
    changes: [
      'Material-Übersicht standardmäßig gruppiert: pro Artikel × Größe Summen für Lager / Ausgegeben / Markiert / Gesamt',
      'Klick auf eine Gruppenzeile öffnet die Einzelteile mit Status, Zuordnung und Zustand',
      'Buttons „Alle auf" / „Alle zu" zum schnellen Auf-/Zuklappen aller Gruppen',
      'Toggle „Gruppiert" / „Einzeln" — die alte ungruppierte Liste bleibt zugänglich',
      'Summenzeile am Tabellenende zeigt Gesamtbestand auf einen Blick',
      'Größen werden in natürlicher Reihenfolge sortiert (XS, S, M, L, XL, XXL, dann Jugend-Größen)',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-05-08',
    changes: [
      'Vereinslogo auf der Login-Seite (100×100) und in der öffentlichen Bedarfsmeldung (80×80)',
      'Favicon im Browser-Tab und auf dem Home-Bildschirm (alle gängigen Größen 16/32/48/96/180/192/512 plus .ico)',
      'Vereinsblau als Theme-Farbe im mobilen Browser-UI',
      'Tab-Titel zeigt jetzt „FC Frohlinde · Trikotverwaltung"',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-08',
    changes: [
      'Lieferanten-Verwaltung in den Einstellungen (Name, Typ, Kontakt, Notizen)',
      'In Bestellungen wählbar: Artikel-Lieferant und Beflockungs-Quelle (Im Haus / Lieferant / extern)',
      'Bei externer Beflockung separater Flock-Lieferant aus der Liste',
      'Material-CSV-Import mit drei Modi: Aktualisieren über Artikelnummer / Hinzufügen / Komplett ersetzen',
      'CSV-Import erkennt Spalten Artikelnummer, Name, Preis, Ersatzwert, Lieferant automatisch',
      'Vorschau vor dem Import zeigt, welche Artikel aktualisiert / neu hinzugefügt werden',
      'Standard-Lieferant für CSV-Zeilen ohne Zuordnung kann beim Import gesetzt werden',
      'Artikelkatalog mit zusätzlichen Spalten: Artikelnummer und Lieferant',
      'Bedarfsmeldungen werden gesperrt, sobald sie in eine Bestellung übernommen wurden (kein doppelter Bestelleingang)',
      'Bestellungen können zusammengeführt werden (Sammelbestellung) — Lines, Bedarfsmeldungen und Sponsoren werden verschmolzen',
      'Beim Löschen einer Bestellung werden gesperrte Bedarfsmeldungen automatisch wieder freigegeben',
      'Sammelbestellungen werden in Übersicht und PDF gekennzeichnet',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-07',
    changes: [
      'Trainer-Bereich mit eigenem Tab und kompletter Logik analog zu Spielern',
      'Automatische Personen-Identifikation bei Bedarfsmeldung (Mannschaft + Nummer)',
      'Automatische Material-Markierung beim Eingang einer Meldung (kein manuelles Klicken mehr)',
      'Foto-Button in der Bedarfs-Übersicht jetzt immer sichtbar (in der Artikel-Spalte)',
      'Fotos werden aggressiver komprimiert (max. 500 KB) für stabile Speicherung',
      'Trainer werden überall mit TRAINER-Badge gekennzeichnet (Material, Pfand, Bestellungen)',
      'Material-Markierungen sind jetzt in der Spieler-/Trainer-Liste als ⚠ Badge sichtbar',
    ],
  },
  {
    version: '1.5.2',
    date: '2026-05-07',
    changes: [
      'Hotfix: MIME-Type-Header für JS-Module in vercel.json korrigiert',
      'PDF-Bibliotheken werden jetzt direkt ins Hauptbundle gepackt (kein Lazy-Loading mehr)',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-05-07',
    changes: [
      'Hotfix: PDF-Export funktioniert jetzt zuverlässig (statischer Import von jspdf, Side-Effect-API)',
      'PDF-Fehler werden sichtbar angezeigt statt stillschweigend zu scheitern',
      'Sicherer Dateiname beim PDF-Speichern',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-07',
    changes: [
      'Mailversand auf SMTP umgestellt (statt Resend) — funktioniert mit jedem Mail-Provider',
      'Test-Mail-Funktion in den Einstellungen mit SMTP-Statusanzeige',
      'Anleitung für SMTP-Einrichtung direkt in der App (mit Beispielen für IONOS, Strato, Telekom, Gmail, M365)',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-05-07',
    changes: [
      'FCF-Pfandordnung 2025 als Standard hinterlegt (Pfand 70 €, 8 Standardteile mit Ersatzwerten)',
      'Zwei Pfandmodi: Pauschal-Modus (FCF-Standard) und Saison-Abschreibung (alt)',
      'Ersatzwert pro Artikel im Katalog editierbar',
      'Total-Verfall des Pfands per Checkbox bei Rückgabe (Punkt 8 Pfandordnung)',
      'Auszug der Pfand- & Kleiderordnung in den Einstellungen',
      'Fotos werden nach 90 Tagen automatisch aus der Datenbank gelöscht',
      'Quick-Action "FCF-Pfandordnung laden" stellt Defaults wieder her',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-07',
    changes: [
      'Foto-Upload bei Bedarfsmeldungen (Browser-Komprimierung auf max. 1280px / ~150 KB)',
      'Foto-Anzeige in der Bedarfsübersicht (Klick öffnet Großansicht)',
      'PDF-Export für Bestellungen mit integrierter Flock-Liste, Sponsoren und Vereins-Branding',
      'Badge mit Anzahl offener Bedarfsmeldungen am Tab "Bedarf"',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-05-07',
    changes: [
      'Hotfix: ReferenceError beim Öffnen der Einstellungen behoben (übersehene Konstante)',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-05-07',
    changes: [
      'Hotfix: Crash beim Öffnen der Einstellungen behoben (Default-Werte für conditionFactors abgesichert)',
      'Error-Boundary: Fehler in einzelnen Bereichen blockieren nicht mehr die ganze App',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-05-07',
    changes: [
      'Bedarfsmeldung für Spieler ohne Login',
      'Editierbare Pfandregeln (Saison-Abschreibung, Zustandsfaktoren)',
      'Wochenbericht über offene Bedarfsmeldungen',
      'Mailversand des Wochenberichts (mit Resend)',
      'Sponsoren-Platzierungen in Bestellungen (Brust, Rücken, Ärmel)',
      'Automatische Material-Markierung aus Spieler-Meldungen',
      'Versionsnummer und Changelog in Einstellungen',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-07',
    changes: [
      'CSV-Import für Spieler mit Validierung und Vorschau',
      'Editorial-Design "Dorfverein" (Vereinsblau, Playfair, Bebas Neue)',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-05-07',
    changes: [
      'Spieler- und Mannschaftsverwaltung',
      'Material- und Bestandsführung',
      'Pfandkasse mit Saison-Rückgabe und Zeitwertberechnung',
      'Bestellungen mit Flock-Liste',
      'Multi-User-Login mit Admin-Rolle',
      'Vercel KV als Datenspeicher',
    ],
  },
];
